version: "3.4"
services:
  web:
    build:
      context: ./
      dockerfile: ./WeatherAPI/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "ABcd1234#Password"
      ACCEPT_EULA: "Y"
